// <auto-generated />
using System;
using ClientRegistry.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClientRegistry.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240924131327_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClientFounder", b =>
                {
                    b.Property<string>("ClientsInn")
                        .HasColumnType("character varying(12)");

                    b.Property<string>("FoundersInn")
                        .HasColumnType("character varying(12)");

                    b.HasKey("ClientsInn", "FoundersInn");

                    b.HasIndex("FoundersInn");

                    b.ToTable("ClientFounder");
                });

            modelBuilder.Entity("ClientRegistry.Models.Client", b =>
                {
                    b.Property<string>("Inn")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Inn");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ClientRegistry.Models.Founder", b =>
                {
                    b.Property<string>("Inn")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Inn");

                    b.ToTable("Founders");
                });

            modelBuilder.Entity("ClientFounder", b =>
                {
                    b.HasOne("ClientRegistry.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsInn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientRegistry.Models.Founder", null)
                        .WithMany()
                        .HasForeignKey("FoundersInn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
